services:
  - type: web
    name: sentrysense-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    runtime: python
    region: oregon
    branch: main
    pythonVersion: 3.11.9
